---

language: node_js

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

node_js: lts/*

cache:
  directories:
    - /tmp/liftoff

script:
  - npm run build
  - npm run lint
  - npm run ci:test

jobs:
  include:
    - stage: Test
      node_js: lts/*
    - node_js: 10
    - node_js: 8

    - stage: Release
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run ci:release
        on:
          repo: elementary/houston
          branch: v2
